name: Release Anki Decks

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install genanki

    - name: Create output directory
      run: mkdir -p output

    - name: Generate Anki Decks
      run: python scripts/generate_deck.py

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: "Release ${{ github.ref_name }}"
        body: |
          This release contains the latest generated Anki decks for Japanese vocabulary learning.
          - Includes both Reading and Listening decks.
        draft: false
        prerelease: false
        overwrite: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload .apkg Files to Release
      uses: actions/upload-release-asset@v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_id: ${{ steps.create_release.outputs.id }}
        asset_path: output/*.apkg
        asset_name: "{{ basename }}"
        asset_content_type: application/octet-stream
