name: Release Anki Decks

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install genanki

    - name: Create output directory
      run: mkdir -p output

    - name: Generate Anki Decks
      run: python scripts/generate_deck.py

    - name: Upload Release Assets
      uses: actions/upload-artifact@v3
      with:
        name: Anki-Decks
        path: output/*.apkg
