name: Release Anki Decks

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: pip install genanki

    # Step 4: Create output directory
    - name: Create output directory
      run: mkdir -p output

    # Step 5: Generate Anki Decks
    - name: Generate Anki Decks
      run: python scripts/generate_deck.py

    # Step 6: Create GitHub Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: "Release ${{ github.ref_name }}"
        body: |
          This release contains the latest generated Anki decks for Japanese vocabulary learning.
          - Includes both Reading and Listening decks.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 7: Upload `.apkg` files as release assets
    - name: Upload .apkg Files
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: output/*.apkg
        asset_name: "{{ basename }}"
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
