name: Release Anki Decks

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: pip install genanki sudachipy sudachidict_core

    # Step 4: Create output directory
    - name: Create output directory
      run: mkdir -p output

    # Step 5: Generate Anki Decks
    - name: Generate Anki Decks
      run: python generate_decks.py

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: output/*.apkg
        tag_name: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}